from datetime import UTC, datetime
from uuid import UUID

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Index, String, text
from sqlalchemy.orm import Mapped, mapped_column

from tiny_hermes.runs.infrastructure import tables as run_tables  # noqa: F401
from tiny_hermes.sandbox.domain.models import (
    LIVE_RESERVATIONS,
    InstanceStatus,
    ReservationStatus,
)
from tiny_hermes.shared.database import Base, CreatedAtMixin, IdMixin

#: The `runs` table this module's one foreign key points at, imported for the
#: reason `skills/infrastructure/tables.py` names its own neighbours: a key
#: resolves by table name at flush time, and the Controller does not import
#: the rest of the platform.
REFERENCED_TABLE_MODULES = (run_tables,)

RESERVATION_STATUSES = tuple(entry.value for entry in ReservationStatus)
INSTANCE_STATUSES = tuple(entry.value for entry in InstanceStatus)
_LIVE = ", ".join(f"'{entry.value}'" for entry in LIVE_RESERVATIONS)


def _in_values(column: str, values: tuple[str, ...]) -> str:
    listed = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({listed})"


class SandboxInstanceRow(IdMixin, CreatedAtMixin, Base):
    """One container.

    **No host path column, and none may be added.** Technical design §6.4 says
    `不保存任意宿主机路径`, and a stored host path is the first half of an
    escape: the caller who could read one is a caller who could ask for it back.
    Every path the container sees is generated by the Controller from this row
    and the configuration, never round-tripped through the database.
    """

    __tablename__ = "sandbox_instances"
    __table_args__ = (
        CheckConstraint(
            _in_values("status", INSTANCE_STATUSES), name="ck_sandbox_instances_status"
        ),
        CheckConstraint(
            "image_digest LIKE 'sha256:%'", name="ck_sandbox_instances_digest"
        ),
    )

    container_id: Mapped[str] = mapped_column(String(128))
    image_digest: Mapped[str] = mapped_column(String(80))
    resource_profile: Mapped[str] = mapped_column(String(40))
    boot_id: Mapped[str] = mapped_column(String(64))
    status: Mapped[str] = mapped_column(String(20))
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )


class SandboxReservationRow(IdMixin, CreatedAtMixin, Base):
    """The platform's claim on a container for one Run.

    The partial unique index is the whole of `acquire`'s "no second sandbox"
    rule. A read-then-write check is a race two Workers can both win; this one
    only one of them can pass. It is partial rather than plain because a Run
    that finished with one sandbox and was retried is entitled to another —
    uniqueness is over live claims, not over history.
    """

    __tablename__ = "sandbox_reservations"
    __table_args__ = (
        Index(
            "uq_sandbox_reservations_live_run",
            "run_id",
            unique=True,
            postgresql_where=text(f"status IN ({_LIVE})"),
        ),
        CheckConstraint(
            _in_values("status", RESERVATION_STATUSES),
            name="ck_sandbox_reservations_status",
        ),
        CheckConstraint(
            "(status = 'kept') = (idle_expires_at IS NOT NULL)",
            name="ck_sandbox_reservations_keep_deadline",
        ),
        CheckConstraint(
            "(status = 'isolated') OR (isolation_reason IS NULL)",
            name="ck_sandbox_reservations_isolation_reason",
        ),
    )

    run_id: Mapped[UUID] = mapped_column()
    workspace_id: Mapped[UUID] = mapped_column()
    sandbox_instance_id: Mapped[UUID] = mapped_column()
    status: Mapped[str] = mapped_column(String(20))
    idle_expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    isolation_reason: Mapped[str | None] = mapped_column(String(80), nullable=True)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )


class SandboxEgressAddressRow(CreatedAtMixin, Base):
    """Which Run a sandbox address belongs to, while it holds one.

    The proxy reads this to answer "who is this" for a caller that presents
    nothing — which is the whole of a sandbox's identity, because a process
    inside a container that holds a credential is one that can lend it.

    Keyed by address rather than by sandbox: two containers cannot have the
    same address at one time, and that is the uniqueness the answer depends on.
    """

    __tablename__ = "sandbox_egress_addresses"

    address: Mapped[str] = mapped_column(String(64), primary_key=True)
    run_id: Mapped[UUID] = mapped_column(
        ForeignKey("runs.id", ondelete="CASCADE"), nullable=False
    )
    sandbox_id: Mapped[UUID] = mapped_column(index=True)
