"""memories

Revision ID: 20260819_0024
Revises: 20260818_0023
Create Date: 2026-08-19 00:11:47.656850
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260819_0024"
down_revision: str | None = "20260818_0023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memories",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("subject_type", sa.String(length=32), nullable=True),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "search",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', body)", persisted=True),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("origin_run_id", sa.Uuid(), nullable=True),
        sa.Column("approval_id", sa.Uuid(), nullable=True),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(kind = 'private') = (subject_type IS NOT NULL AND subject_id IS NOT NULL)",
            name="ck_memories_subject_matches_kind",
        ),
        sa.CheckConstraint("kind IN ('private', 'shared')", name="ck_memories_kind"),
        sa.CheckConstraint(
            "status IN ('pending', 'active', 'rejected')", name="ck_memories_status"
        ),
        sa.CheckConstraint(
            "subject_type IS NULL OR subject_type IN ('user', 'service_account')",
            name="ck_memories_subject_type",
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_memories_created_by", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_memories_scope",
        "memories",
        ["workspace_id", "agent_id", "kind", "subject_type", "subject_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_memories_search", "memories", ["search"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_memories_workspace_id"), "memories", ["workspace_id"], unique=False)
    op.add_column(
        "workspaces",
        sa.Column(
            "memory_policy", sa.String(length=16), server_default="all_pending", nullable=False
        ),
    )
    op.create_check_constraint(
        "ck_workspaces_memory_policy",
        "workspaces",
        "memory_policy IN ('off', 'all_pending', 'low_risk_auto')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_workspaces_memory_policy", "workspaces", type_="check")
    op.drop_column("workspaces", "memory_policy")
    op.drop_index(op.f("ix_memories_workspace_id"), table_name="memories")
    op.drop_index("ix_memories_search", table_name="memories", postgresql_using="gin")
    op.drop_index("ix_memories_scope", table_name="memories")
    op.drop_table("memories")
    # ### end Alembic commands ###
